services:
  es:
    image: elasticsearch:8.18.2
    container_name: elasticsearch
    ports:
      - 19200:9200
      - 19300:9300
    environment:
      TZ: Asia/Shanghai
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      xpack.security.enabled: false
      ELASTIC_PASSWORD: fouL*X0n^CH8
      discovery.type: single-node
      ingest.geoip.downloader.enabled: false
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s

  jaeger:
    image: jaegertracing/jaeger:2.7.0
    container_name: jaeger
    ports:
      - 16686:16686
      - 14317:4317
      - 14318:4318
    environment:
      LOG_LEVEL: debug
      TZ: Asia/Shanghai
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://es:19200
      ES_USERNAME: elastic
      ES_PASSWORD: fouL*X0n^CH8
    # healthcheck:
    #   test: ["CMD", "curl", "localhost:13133/status"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 15s
    depends_on:
      es:
        condition: service_healthy
        restart: true

  redis:
    image: redis:7.4.4
    container_name: redis
    environment:
      - TZ=Asia/Shanghai
    command: redis-server --requirepass W*5rE#8l7
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a W*5rE#8l7", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 16379:6379

  postgres:
    image: postgres:16-alpine
    ports:
      - "15432:5432"
    container_name: postgresql
    # volumes:
    #   - /home/wqh/components/postgresql/data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=P3g5R$1*b7
      - POSTGRES_USER=heibai
      - POSTGRES_DB=slotgame
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heibai -d slotgame"]
      interval: 5s
      timeout: 5s
      retries: 5
